# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d6504a29a83c48d9ba489862ddcdf2f00439c5ec7473c79670ff6a822c17489d64b38562426d5670d67b843bf812ead2700ed71e5aa79029657c3e143515cb

test:
  secret_key_base: 09257165471025e6164e724e9491cc47d78d7b2b6323f495db6c8407b37bf977f7a2c2f1301d5c59a8698daf2d8de4cb9145fa7f7c25d6242f18ef1acdf62cc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
